services:
  ${{ values.service_name }}:
    build:
      target: development
    image: ${{ values.service_name }}-development
    container_name: ${{ values.service_name }}-test
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./${{ values.dotnet_solution_name }}.sln:/home/dotnet/${{ values.dotnet_solution_name }}.sln
      - ./src/${{ values.dotnet_solution_name }}.Core:/home/dotnet/src/${{ values.dotnet_solution_name }}.Core
      - ./test/${{ values.dotnet_solution_name }}.Core.Tests:/home/dotnet/test/${{ values.dotnet_solution_name }}.Core.Tests
      - ./src/${{ values.dotnet_solution_name }}.Api:/home/dotnet/src/${{ values.dotnet_solution_name }}.Api
      - ./test/${{ values.dotnet_solution_name }}.Api.Tests:/home/dotnet/test/${{ values.dotnet_solution_name }}.Api.Tests
      - ./test/${{ values.dotnet_solution_name }}.Api.Tests/test-output:/home/dotnet/test/${{ values.dotnet_solution_name }}.Api.Tests/test-output
      - ./test/${{ values.dotnet_solution_name }}.Core.Tests/test-output:/home/dotnet/test/${{ values.dotnet_solution_name }}.Core.Tests/test-output
