services:
  adp-backend-template-dotnet:
    build:
      context: .
      target: production
    image: adp-backend-template-dotnet
    container_name: adp-backend-template-dotnet
    environment:
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APPINSIGHTS_CLOUDROLE: adp-backend-template-dotnet-local