parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployConfigOnly
    displayName: "Deploy App Config & Secrets Only"
    type: boolean
    default: false     
pr:
  branches:
    include:
      - main
      - master
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: rv/manifestpathtest

extends:
  template: /pipelines/common-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    programmeName: ""
    teamName: "adp-demo"
    serviceName: "adp-backend-template-dotnet"
    deployFromFeature: ${{ parameters.deployFromFeature }}
    appBuildConfig:
      appFrameworkType: "dotnet"
      frameworkVersion: "8.x"    
      projectPath: "./src/ADP.Backend.Template.Api/ADP.Backend.Template.Api.csproj"
      testProjectPath: "**/*.Tests.csproj" 
      manifestPath: "./src/obj/ADP.Backend.Template.Api/project.assets.json;./src/obj/ADP.Backend.Template.Core/project.assets.json"
      imageRepoName: "adp-backend-template-dotnet"
    appTestConfig:
      testFilePath: ""
    appDeployConfig:
      filepath: "./appConfig"
      filetype: "yaml" 
      # variableGroups: 
      #   - adp-backend-template-dotnet-<environment> 